---
# Replace the fields below with relevant information.
# See https://www.mkdocs.org/user-guide/configuration/
# to learn more about the configuration options.
site_name: Ansible project template
site_url: https://ansible.readthedocs.io/PROJECTNAME
repo_url: https://github.com/ansible-community/project-template
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: 'ansible'
  features:
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - toc.integrate

nav:
  - Home: 'index.md'
  - Installation: 'installing.md'
  - Getting started: 'getting_started_user.md'
  - User guide:
    - 'user_guide.md'
    - 'user_guide/how_to_xxx.md'
  - 'contributor_guide.md'
  - 'maintainer_guide.md'
  - 'community_guide.md'
  - References:
    - 'references/cli.md'
    - 'references/porting_guide.md'
    - 'references/roadmap.md'
  - 'License': 'license.md'
